name=APacketeer
version=1.0.0
author=SebLit
maintainer=SebLit
sentence=Arduino port of JPacketeer. Protocol for lightweight network communication
paragraph=
category=Communication
url=https://github.com/SebLit/APacketeer
architectures=*
depends=